apiVersion: v1
kind: Service
metadata:
  name: mmtc-slice
  namespace: pdc-nsd
  labels: 
    app: mmtc-slice
spec:
  type: ClusterIP
  selector:
    app: mmtc-slice
  ports:
  - protocol: TCP
    port: 8103
    targetPort: 8103
