apiVersion: v1
kind: Service
metadata:
  name: urllc-slice
  namespace: pdc-nsd
  labels: 
    app: urllc-slice
spec:
  type: ClusterIP
  selector:
    app: urllc-slice
  ports:
  - protocol: TCP
    port: 8102
    targetPort: 8102
