apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pdc-nsd

resources:
  - deploy/base
  - deploy/backend
  - deploy/slices
  - deploy/scheduler
  - deploy/frontend
  - deploy/SQL
