apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: NSD_database_pvc
  namespace: pdc_backend
  labels:
   app: database_pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  