apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: pdc-nsd
data:
  # Connection details for the backend to find the database
  MYSQL_HOST: "backend-db"
  MYSQL_USER: "nsd_user"       # <--- CHANGED from 'root' to match SQL Deployment
  MYSQL_DATABASE: "nsd_db"     
  BACKEND_PORT: "8000"