apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: pdc-nsd
type: Opaque
data:
  # ðŸ‘‡ This is "nsd_pass" encoded (Matches your SQL Deployment)
  MYSQL_PASSWORD: bnNkX3Bhc3M=
  
  # ðŸ‘‡ This is "root123" encoded (Root password)
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==