apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: pdc-nsd
spec:
  type: ClusterIP
  selector:
    app: scheduler        # MUST match deployment.labels.app
  ports:
    - name: http
      protocol: TCP
      port: 8001          # service port
      targetPort: 8001    # containerPort from deployment
