apiVersion: v1 
kind: Service
metadata:
  name: backend-db
  namespace: pdc-nsd
spec:
  type: ClusterIP
  selector:
    app: sql-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

  
